-- Legacy Netbanking Database Schema
-- SQLite

CREATE TABLE IF NOT EXISTS USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER'
);

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    account_number VARCHAR(20) NOT NULL UNIQUE,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    from_account INTEGER NOT NULL,
    to_account INTEGER NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    description VARCHAR(200),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (from_account) REFERENCES ACCOUNTS(id),
    FOREIGN KEY (to_account) REFERENCES ACCOUNTS(id)
);

CREATE INDEX IF NOT EXISTS idx_accounts_user_id ON ACCOUNTS(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_from ON TRANSACTIONS(from_account);
CREATE INDEX IF NOT EXISTS idx_transactions_to ON TRANSACTIONS(to_account);
